COMMENT ON TABLE "TJ_REAP_CALENDAR" IS 'The reference product reaping calendar';
COMMENT ON COLUMN "TJ_REAP_CALENDAR".rpc_id IS 'The product ';
COMMENT ON COLUMN "TJ_REAP_CALENDAR".rmn_id IS 'The reap mont';
COMMENT ON TABLE "TJ_SEED_CALENDAR" IS 'The reference month of seedling product';
COMMENT ON COLUMN "TJ_SEED_CALENDAR".rpc_id IS 'The reference product';
COMMENT ON COLUMN "TJ_SEED_CALENDAR".rmn_id IS 'The seed month';
COMMENT ON TABLE "T_ADDRESS" IS 'The address of the user and/or the garden';
COMMENT ON COLUMN "T_ADDRESS.ADR_ID" IS 'The database id';
COMMENT ON COLUMN "T_ADDRESS.ADR_NAME" IS 'The address name. This is a user information';
COMMENT ON COLUMN "T_ADDRESS.ADR_STREET_NUMBER" IS 'The street number';
COMMENT ON COLUMN "T_ADDRESS.ADR_STREET_NAME" IS 'The address line one';
COMMENT ON COLUMN "T_ADDRESS.ADR_RCI_ID" IS 'The city address';
COMMENT ON COLUMN "T_ADDRESS.ADR_LATITUDE" IS 'The latitude address, based on google information';
COMMENT ON COLUMN "T_ADDRESS.ADR_LONGITUDE" IS 'The longitude address, based on google information';
COMMENT ON COLUMN "T_ADDRESS.ADR_LOCALITY" IS 'The address city name';
COMMENT ON COLUMN "T_ADDRESS.ADR_ADM_AREA_L2" IS 'The address administrative areal level 2';
COMMENT ON COLUMN "T_ADDRESS.ADR_ADM_AREA_L1" IS 'The address administrative areal level 2';
COMMENT ON COLUMN "T_ADDRESS.ADR_COUNTRY" IS 'The address country';
COMMENT ON COLUMN "T_ADDRESS.ADR_POSTAL_CODE" IS 'The address postal code';
COMMENT ON TABLE "T_COMMENT_GARDEN" IS 'List of the comment made on gardens';
COMMENT ON COLUMN "T_COMMENT_GARDEN".cgr_id IS 'The database id';
COMMENT ON COLUMN "T_COMMENT_GARDEN".cgr_comment IS 'The comment left';
COMMENT ON COLUMN "T_COMMENT_GARDEN".cgr_creation_date IS 'The creation date of the comment';
COMMENT ON COLUMN "T_COMMENT_GARDEN".cgr_res_id IS 'The comment status';
COMMENT ON COLUMN "T_COMMENT_GARDEN".cgr_grd_id IS 'The garden commented';
COMMENT ON COLUMN "T_COMMENT_GARDEN".cgr_usr_id IS 'The user leaving the comment';
COMMENT ON COLUMN "T_COMMENT_GARDEN".cgr_ren_id IS 'The evaluation note';
COMMENT ON TABLE "T_COMMENT_PRODUCT" IS 'List of comment made on the product';
COMMENT ON COLUMN "T_COMMENT_PRODUCT".cpr_id IS 'The database id';
COMMENT ON COLUMN "T_COMMENT_PRODUCT".cpr_comment IS 'The comment write';
COMMENT ON COLUMN "T_COMMENT_PRODUCT".cpr_creation_date IS 'The date of when was write';
COMMENT ON COLUMN "T_COMMENT_PRODUCT".cpr_res_id IS 'The evaluation status';
COMMENT ON COLUMN "T_COMMENT_PRODUCT".cpr_prd_id IS 'The product being commented';
COMMENT ON COLUMN "T_COMMENT_PRODUCT".cpr_usr_id IS 'The user writing the comment';
COMMENT ON COLUMN "T_COMMENT_PRODUCT".cpr_ren_id IS 'The value of the note';
COMMENT ON TABLE "T_GARDEN" IS 'The garden';
COMMENT ON COLUMN "T_GARDEN".grd_id IS 'The database id';
COMMENT ON COLUMN "T_GARDEN".grd_creation_date IS 'The date the garden was create';
COMMENT ON COLUMN "T_GARDEN".grd_description IS 'The user description of the garden';
COMMENT ON COLUMN "T_GARDEN".grd_name IS 'A user visible address name';
COMMENT ON COLUMN "T_GARDEN".grd_img_filename IS 'The image file name of the garden';
COMMENT ON COLUMN "T_GARDEN".grd_usr_id IS 'The owner';
COMMENT ON COLUMN "T_GARDEN".grd_ADR_id IS 'The garden address';
COMMENT ON TABLE "T_LIKE_GARDEN" IS 'The list of garden like by user';
COMMENT ON COLUMN "T_LIKE_GARDEN".lgr_id IS 'The database id';
COMMENT ON COLUMN "T_LIKE_GARDEN".lgr_creation_date IS 'The creation date of the like';
COMMENT ON COLUMN "T_LIKE_GARDEN".lgr_res_id IS 'The evaluation status';
COMMENT ON COLUMN "T_LIKE_GARDEN".lgr_grd_id IS 'The garden evaluated';
COMMENT ON COLUMN "T_LIKE_GARDEN".lgr_usr_id IS 'The user that like the garden';
COMMENT ON TABLE "T_LIKE_PRODUCT" IS 'The list of product like by user';
COMMENT ON COLUMN "T_LIKE_PRODUCT".lpr_id IS 'The database id';
COMMENT ON COLUMN "T_LIKE_PRODUCT".lpr_creation_date IS 'The date when the like have been created';
COMMENT ON COLUMN "T_LIKE_PRODUCT".lpr_res_id IS 'The evaluation status';
COMMENT ON COLUMN "T_LIKE_PRODUCT".lpr_prd_id IS 'The product';
COMMENT ON COLUMN "T_LIKE_PRODUCT".lpr_usr_id IS 'The user who like the product';
COMMENT ON TABLE "T_PRODUCT" IS 'The product made by user';
COMMENT ON COLUMN "T_PRODUCT".prd_id IS 'The database id';
COMMENT ON COLUMN "T_PRODUCT".prd_rcm_id IS 'The culture mode';
COMMENT ON COLUMN "T_PRODUCT".prd_rct_id IS 'The culture type';
COMMENT ON COLUMN "T_PRODUCT".prd_description IS 'The user description of the product';
COMMENT ON COLUMN "T_PRODUCT".prd_rct_id IS 'The exchange type';
COMMENT ON COLUMN "T_PRODUCT".prd_img_filename IS 'The file name of the product image';
COMMENT ON COLUMN "T_PRODUCT".prd_quantity IS 'The quantity left available to exchange';
COMMENT ON COLUMN "T_PRODUCT".prd_grd_id IS 'The garden where the product grow';
COMMENT ON COLUMN "T_PRODUCT".prd_rpc_id IS 'The reference product';
COMMENT ON TABLE "T_PROFIL" IS 'User profil';
COMMENT ON COLUMN "T_PROFIL".prf_id IS 'The database id.';
COMMENT ON COLUMN "T_PROFIL".prf_experience IS 'A user experience of free veggie';
COMMENT ON COLUMN "T_PROFIL".prf_interest IS 'The interest of the user ';
COMMENT ON COLUMN "T_PROFIL".prf_other IS 'Anything else that the user wanted to say';
COMMENT ON COLUMN "T_PROFIL".prf_participation IS 'A description why the user subscribe';
COMMENT ON COLUMN "T_PROFIL".prf_description IS 'A description of the user';
COMMENT ON COLUMN "T_PROFIL".prf_philosophy IS 'Life philosophies of the user';
COMMENT ON COLUMN "T_PROFIL".prf_meals IS 'The prefered meal of the user';
COMMENT ON COLUMN "T_PROFIL".prf_img_filename IS 'The file name of the user picture';
COMMENT ON COLUMN "T_PROFIL".prf_reason IS 'The reason why the user got to this website';
COMMENT ON TABLE "T_REF_COUNTRY" IS 'The list of country';
COMMENT ON COLUMN "T_REF_COUNTRY".rcn_code_iso_a2 IS 'The is 2 letters code';
COMMENT ON COLUMN "T_REF_COUNTRY".rcn_code_iso_a3 IS 'The iso 3 letters code';
COMMENT ON COLUMN "T_REF_COUNTRY".rcn_code_iso_number IS 'The iso code number';
COMMENT ON COLUMN "T_REF_COUNTRY".rcn_country_name IS 'The country name';
COMMENT ON TABLE "T_REF_CULTURE_MODE" IS 'The choice of culture mode';
COMMENT ON COLUMN "T_REF_CULTURE_MODE".rcm_id IS 'The database id';
COMMENT ON COLUMN "T_REF_CULTURE_MODE".rcm_libelle IS 'The culture mode description ';
COMMENT ON TABLE "T_REF_CULTURE_TYPE" IS 'The choice of culture type';
COMMENT ON COLUMN "T_REF_CULTURE_TYPE".rct_id IS 'The database id';
COMMENT ON COLUMN "T_REF_CULTURE_TYPE".rct_libelle IS 'The culture type description';
COMMENT ON TABLE "T_REF_EVALUATION_NOTE" IS 'The value of a note (for a garden or a product)';
COMMENT ON COLUMN "T_REF_EVALUATION_NOTE".ren_id IS 'The database id';
COMMENT ON COLUMN "T_REF_EVALUATION_NOTE".ren_libelle IS 'The evaluation note description';
COMMENT ON TABLE "T_REF_EVALUATION_STATUS" IS 'The status of an evaluation(product, garden, ...)';
COMMENT ON COLUMN "T_REF_EVALUATION_STATUS".res_id IS 'The database id';
COMMENT ON COLUMN "T_REF_EVALUATION_STATUS".res_libelle IS 'The evaluation status description';
COMMENT ON TABLE "T_REF_EXCHANGE_TYPE" IS 'Choice of exchange type';
COMMENT ON COLUMN "T_REF_EXCHANGE_TYPE".chg_id IS 'The database id';
COMMENT ON COLUMN "T_REF_EXCHANGE_TYPE".chg_libelle IS 'The exchange type description';
COMMENT ON TABLE "T_REF_MONTH" IS 'The reference mont of a year';
COMMENT ON COLUMN "T_REF_MONTH".rmn_id IS 'The month number';
COMMENT ON COLUMN "T_REF_MONTH".rmn_name IS 'The month description';
COMMENT ON TABLE "T_REF_PRODUCT" IS 'The reference of product';
COMMENT ON COLUMN "T_REF_PRODUCT".rpc_id IS 'The database id';
COMMENT ON COLUMN "T_REF_PRODUCT".rpc_carbohydrate IS 'The quantity of carbohydrate in the product';
COMMENT ON COLUMN "T_REF_PRODUCT".rpc_lipid IS 'The quantity of lipid in the product';
COMMENT ON COLUMN "T_REF_PRODUCT".rpc_name IS 'The name of the product gived by the producer';
COMMENT ON COLUMN "T_REF_PRODUCT".rpc_img_filename IS 'The file name of the product image';
COMMENT ON COLUMN "T_REF_PRODUCT".rpc_protein IS 'The quantity of protein in the product';
COMMENT ON COLUMN "T_REF_PRODUCT".rpc_rpt_id IS 'The product type';
COMMENT ON TABLE "T_REF_PRODUCT_REQUEST_STATUS" IS 'The posible state of a product request';
COMMENT ON COLUMN "T_REF_PRODUCT_REQUEST_STATUS".rpr_id IS 'The database id';
COMMENT ON COLUMN "T_REF_PRODUCT_REQUEST_STATUS".rpr_libelle IS 'The product request status description';
COMMENT ON TABLE "T_REF_PRODUCT_TYPE" IS 'The reference of product type (fruit or vegetable)';
COMMENT ON COLUMN "T_REF_PRODUCT_TYPE".rpt_id IS 'The database id';
COMMENT ON COLUMN "T_REF_PRODUCT_TYPE".rpt_libelle IS 'The product type description';
COMMENT ON TABLE "T_REF_RELATIONS_STATUS" IS 'The posible state of relationship';
COMMENT ON COLUMN "T_REF_RELATIONS_STATUS".rrs_id IS 'The database id.';
COMMENT ON COLUMN "T_REF_RELATIONS_STATUS".rrs_libelle IS 'The relation status description';
COMMENT ON TABLE "T_REF_RELATION_TYPE" IS 'The possible value of a relation type (friends, neighbors, ...)';
COMMENT ON COLUMN "T_REF_RELATION_TYPE".rrt_id IS 'The database id';
COMMENT ON COLUMN "T_REF_RELATION_TYPE".rrt_libelle IS 'The relation description';
COMMENT ON TABLE "T_REF_USER_ROLE" IS 'The posible user role';
COMMENT ON COLUMN "T_REF_USER_ROLE".rur_id IS 'The database id';
COMMENT ON COLUMN "T_REF_USER_ROLE".rur_libelle IS 'The user role description';
COMMENT ON TABLE "T_REF_USER_STATUS" IS 'The possible state of user (new, blacklisted, ....)';
COMMENT ON COLUMN "T_REF_USER_STATUS".rus_libelle IS 'The user status description';
COMMENT ON TABLE "T_RELATIONSHIP" IS 'The list of user relationship';
COMMENT ON COLUMN "T_RELATIONSHIP".rlt_id IS 'The database id';
COMMENT ON COLUMN "T_RELATIONSHIP".rlt_answer IS 'The answer of the request';
COMMENT ON COLUMN "T_RELATIONSHIP".rlt_creation_date IS 'The date and time when the request was send';
COMMENT ON COLUMN "T_RELATIONSHIP".rlt_rrs_id IS 'The relation status';
COMMENT ON COLUMN "T_RELATIONSHIP".rlt_rrt_id IS 'The type of relationship';
COMMENT ON COLUMN "T_RELATIONSHIP".rlt_usr_id_sender IS 'The user who send the request';
COMMENT ON COLUMN "T_RELATIONSHIP".rlt_usr_id_recipient IS 'The recipient of the request.';
COMMENT ON COLUMN "T_RELATIONSHIP".rlt_request IS 'The request messages send from the recipient';
COMMENT ON TABLE "T_REQUEST_PRODUCT" IS 'The product request made by users';
COMMENT ON COLUMN "T_REQUEST_PRODUCT".rqt_id IS 'The database id';
COMMENT ON COLUMN "T_REQUEST_PRODUCT".rqt_answer_msg IS 'The request answer';
COMMENT ON COLUMN "T_REQUEST_PRODUCT".rqt_answer_date IS 'The date the user answer the request';
COMMENT ON COLUMN "T_REQUEST_PRODUCT".rqt_creation_date IS 'The date of the request have been send';
COMMENT ON COLUMN "T_REQUEST_PRODUCT".rqt_msg IS 'The request message send by the requester';
COMMENT ON COLUMN "T_REQUEST_PRODUCT".rqt_picking_date IS 'The date that the requester wish to pick the product';
COMMENT ON COLUMN "T_REQUEST_PRODUCT".rqt_quantity IS 'The quantity the request wish to pick';
COMMENT ON COLUMN "T_REQUEST_PRODUCT".rqt_rpr_id IS 'The request status';
COMMENT ON COLUMN "T_REQUEST_PRODUCT".rqt_prd_id IS 'The product requested';
COMMENT ON COLUMN "T_REQUEST_PRODUCT".rqt_usr_id IS 'The user who send the request';
COMMENT ON TABLE "T_SUBSCRIPTION" IS 'The subscription of the user';
COMMENT ON COLUMN "T_SUBSCRIPTION".sbr_id IS 'The database id';
COMMENT ON COLUMN "T_SUBSCRIPTION".sbr_share_personal IS 'Does the user agree to share his personal information with free veggie partners';
COMMENT ON COLUMN "T_SUBSCRIPTION".sbr_share_garden IS 'Does the user agree to share his garden information to free veggie partners';
COMMENT ON COLUMN "T_SUBSCRIPTION".sbr_newsletter IS 'Does the user agree to receive the free veggie newsletter';
COMMENT ON COLUMN "T_SUBSCRIPTION".sbr_freeveggie_agreement IS 'Does the user sign the freeveggie aggreement';
COMMENT ON TABLE "T_USER" IS 'The website users';
COMMENT ON COLUMN "T_USER".usr_id IS 'The database id';
COMMENT ON COLUMN "T_USER".usr_blacklisted_date IS 'The date when the user got blacklisted';
COMMENT ON COLUMN "T_USER".usr_cancellation_date IS 'The date when the user cancel his subscription';
COMMENT ON COLUMN "T_USER".usr_creation_date IS 'The date when the account get create';
COMMENT ON COLUMN "T_USER".usr_email_address IS 'The user email address';
COMMENT ON COLUMN "T_USER".usr_firstname IS 'The user firstname';
COMMENT ON COLUMN "T_USER".usr_last_connexion IS 'The user last connexion date and time';
COMMENT ON COLUMN "T_USER".usr_lastname IS 'The user last name';
COMMENT ON COLUMN "T_USER".usr_password IS 'The user password encrypted user MD5';
COMMENT ON COLUMN "T_USER".usr_rur_id IS 'The user role ';
COMMENT ON COLUMN "T_USER".usr_rus_id IS 'The user status ';
COMMENT ON COLUMN "T_USER".usr_temp_password IS 'The user temporary password. Create after the user ask for a new one because he lost his password. Encrypted under the MD5 algorithme';
COMMENT ON COLUMN "T_USER".usr_username IS 'The user login';
COMMENT ON COLUMN "T_USER".usr_ADR_id IS 'The user address';
COMMENT ON COLUMN "T_PICTURE_GARDEN".grp_id IS 'Database id';
COMMENT ON COLUMN "T_PICTURE_GARDEN".grp_mine_type IS 'Thie picture mine type';
COMMENT ON COLUMN "T_PICTURE_GARDEN".grp_grd_id IS 'Garden Id';
COMMENT ON COLUMN "T_PICTURE_GARDEN".picture IS 'The picture. In byte.';
COMMENT ON COLUMN "T_PICTURE_GARDEN".grp_creation_date IS 'The picture creation date.';
COMMENT ON COLUMN "T_PICTURE_PRODUCT".prp_id IS 'Database id';
COMMENT ON COLUMN "T_PICTURE_PRODUCT".prp_mine_type IS 'The picture mine type';
COMMENT ON COLUMN "T_PICTURE_PRODUCT".prp_prd_id IS 'Garden Id';
COMMENT ON COLUMN "T_PICTURE_PRODUCT".picture IS 'The picture. In byte.';
COMMENT ON COLUMN "T_PICTURE_PRODUCT".prp_creation_date IS 'The picture creation date.';